// <auto-generated />
namespace Movie_Mania.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class genremodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genremodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202308302029500_genremodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
